/**
 * Round-Trip XSD Validation Tests (FIX-2.4)
 *
 * Validates that XML generated by our generators passes
 * real SAT Anexo 24 v1.3 XSD schema validation via xmllint.
 */

import { describe, expect, it } from 'vitest';
import { validateSatXml } from '@repo/sat-schemas';
import { generateCatalogXml } from '../catalog-xml';
import { generateBalanceXml } from '../balance-xml';
import { generateJournalXml } from '../journal-xml';
import type { Account, TrialBalanceRow, JournalEntry, JournalEntryLine } from '../../types';

async function validateXml(xml: string, schemaType: string) {
  const result = await validateSatXml(xml, schemaType);
  return {
    valid: result.valid,
    errors: result.errors.map(e => `Line ${e.line}: ${e.message}`),
  };
}

// ---- Factories ----

const makeAccount = (overrides: Partial<Account> = {}): Account => ({
  id: 'acc-1',
  organizationId: 'org-1',
  code: '1001',
  name: 'Caja',
  satAgrupadorCode: '101.01',
  satNivel: 2,
  satNaturaleza: 'D',
  materializedPath: '1000.1001',
  isPostable: true,
  accountType: 'asset',
  normalBalance: 'D',
  currencyCode: 'MXN',
  requiresUuid: false,
  requiresThirdParty: false,
  isActive: true,
  isSystem: false,
  effectiveFrom: '2026-01-01',
  createdAt: '2026-01-01',
  updatedAt: '2026-01-01',
  ...overrides,
});

const makeRow = (overrides: Partial<TrialBalanceRow> = {}): TrialBalanceRow => ({
  accountId: 'acc-1',
  accountCode: '1001',
  accountName: 'Caja',
  satAgrupadorCode: '101.01',
  satNivel: 2,
  satNaturaleza: 'D',
  openingDebit: 10000,
  openingCredit: 0,
  periodDebit: 5000,
  periodCredit: 3000,
  closingDebit: 12000,
  closingCredit: 0,
  ...overrides,
});

const makeLine = (overrides: Partial<JournalEntryLine> = {}): JournalEntryLine => ({
  id: 'line-1',
  organizationId: 'org-1',
  journalEntryId: 'entry-1',
  lineNumber: 1,
  accountId: 'acc-1',
  accountCode: '1104',
  debit: 1160.50,
  credit: 0,
  description: 'Cargo a clientes',
  createdAt: '2026-01-15',
  ...overrides,
});

const makeEntry = (overrides: Partial<JournalEntry> = {}): JournalEntry => ({
  id: 'entry-1',
  organizationId: 'org-1',
  entryNumber: '2026-000001',
  fiscalPeriodId: 'period-1',
  entryDate: '2026-01-15',
  polizaType: 'ingreso',
  description: 'Factura A-001',
  status: 'posted',
  currencyCode: 'MXN',
  exchangeRate: 1,
  totalDebit: 1160.50,
  totalCredit: 1160.50,
  lines: [
    makeLine({ lineNumber: 1, accountId: 'acc-1', accountCode: '1104', debit: 1160.50, credit: 0 }),
    makeLine({ lineNumber: 2, accountId: 'acc-2', accountCode: '4101', debit: 0, credit: 1000 }),
    makeLine({ lineNumber: 3, accountId: 'acc-3', accountCode: '2104', debit: 0, credit: 160.50 }),
  ],
  createdAt: '2026-01-15',
  createdBy: 'user-1',
  updatedAt: '2026-01-15',
  ...overrides,
});

// ---- Tests ----

describe('Round-trip XSD Validation — Catalog (CT)', () => {
  it('generated catalog XML should pass XSD validation', async () => {
    const parent = makeAccount({ id: 'p1', code: '1000', name: 'Activo', satAgrupadorCode: '100', satNivel: 1 });
    const child = makeAccount({ id: 'c1', code: '1001', name: 'Caja', satAgrupadorCode: '101.01', satNivel: 2, parentId: 'p1' });

    const xml = generateCatalogXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      accounts: [parent, child],
    });

    const result = await validateXml(xml, 'CT');
    expect(result.valid).toBe(true);
    if (!result.valid) {
      console.error('XSD errors:', result.errors);
    }
  });

  it('generated catalog XML with multiple account types should pass XSD', async () => {
    const accounts = [
      makeAccount({ id: 'a1', code: '1000', name: 'Activo', satAgrupadorCode: '100', satNivel: 1 }),
      makeAccount({ id: 'a2', code: '1001', name: 'Caja', satAgrupadorCode: '101.01', satNivel: 2, parentId: 'a1' }),
      makeAccount({ id: 'a3', code: '2000', name: 'Pasivo', satAgrupadorCode: '200', satNivel: 1, satNaturaleza: 'A', accountType: 'liability' }),
      makeAccount({ id: 'a4', code: '2001', name: 'Proveedores', satAgrupadorCode: '201.01', satNivel: 2, satNaturaleza: 'A', parentId: 'a3', accountType: 'liability' }),
    ];

    const xml = generateCatalogXml({
      rfc: 'XAXX010101000',
      month: 3,
      year: 2026,
      accounts,
    });

    const result = await validateXml(xml, 'CT');
    expect(result.valid).toBe(true);
  });
});

describe('Round-trip XSD Validation — Balance (BN)', () => {
  it('generated balance XML should pass XSD validation', async () => {
    const xml = generateBalanceXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipo: 'N',
      rows: [makeRow()],
    });

    const result = await validateXml(xml, 'BN');
    expect(result.valid).toBe(true);
    if (!result.valid) {
      console.error('XSD errors:', result.errors);
    }
  });

  it('generated complementaria balance XML should pass XSD', async () => {
    const xml = generateBalanceXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipo: 'C',
      rows: [makeRow()],
      fechaModBal: '2026-02-15',
    });

    const result = await validateXml(xml, 'BC');
    expect(result.valid).toBe(true);
  });

  it('generated balance with negative saldo should pass XSD', async () => {
    const xml = generateBalanceXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipo: 'N',
      rows: [makeRow({
        satNaturaleza: 'D',
        openingDebit: 0,
        openingCredit: 500,
        closingDebit: 0,
        closingCredit: 500,
      })],
    });

    const result = await validateXml(xml, 'BN');
    expect(result.valid).toBe(true);
  });
});

describe('Round-trip XSD Validation — Polizas (PL)', () => {
  const accountNames = new Map<string, string>([
    ['acc-1', 'Clientes'],
    ['acc-2', 'Ventas'],
    ['acc-3', 'IVA Trasladado'],
  ]);

  it('generated polizas XML should pass XSD validation', async () => {
    const xml = generateJournalXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipoSolicitud: 'AF',
      numOrden: 'ABC1234567/01',
      entries: [makeEntry()],
      accountNames,
    });

    const result = await validateXml(xml, 'PL');
    expect(result.valid).toBe(true);
    if (!result.valid) {
      console.error('XSD errors:', result.errors);
    }
  });

  it('generated polizas with CompNal should pass XSD', async () => {
    const entry = makeEntry({
      lines: [
        makeLine({
          accountCode: '1104',
          debit: 1160.50,
          credit: 0,
          uuidCfdi: '550e8400-e29b-41d4-a716-446655440000',
          rfcThirdParty: 'XAXX010101000',
          montoTotalComp: 1160.50,
        }),
        makeLine({ lineNumber: 2, accountId: 'acc-2', accountCode: '4101', debit: 0, credit: 1160.50 }),
      ],
    });

    const xml = generateJournalXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipoSolicitud: 'AF',
      numOrden: 'ABC1234567/01',
      entries: [entry],
      accountNames,
    });

    const result = await validateXml(xml, 'PL');
    expect(result.valid).toBe(true);
  });
});

describe('Regression guards — XSD validation', () => {
  it('no BanEmworCheworNal typo in generated journal XML', async () => {
    const entry = makeEntry({
      lines: [
        makeLine({
          accountCode: '1102',
          debit: 0,
          credit: 3000,
          paymentMethod: 'cheque',
          paymentReference: '00012345',
          bankCode: '012',
          bankAccount: '0012345678',
          paymentDate: '2026-01-15',
          paymentBeneficiary: 'Test Prov',
          paymentBeneficiaryRfc: 'XAXX010101000',
        }),
        makeLine({ lineNumber: 2, accountId: 'acc-2', accountCode: '6101', debit: 3000, credit: 0 }),
      ],
    });

    const accountNames = new Map<string, string>([
      ['acc-1', 'Bancos'],
      ['acc-2', 'Gastos Generales'],
    ]);

    const xml = generateJournalXml({
      rfc: 'XAXX010101000',
      month: 1,
      year: 2026,
      tipoSolicitud: 'AF',
      numOrden: 'ABC1234567/01',
      entries: [entry],
      accountNames,
    });

    expect(xml).not.toContain('BanEmworCheworNal');
    expect(xml).toContain('BanEmisNal="012"');
  });
});
