-- Migration: Add embedding column to sat_product_codes for AI-powered search
-- Component 9: SAT Code Search Service (AI-Powered)

-- Enable pgvector extension if not already enabled
CREATE EXTENSION IF NOT EXISTS vector;

-- Add embedding column to sat_product_codes table
-- Using 384 dimensions for paraphrase-multilingual-MiniLM-L12-v2 model
ALTER TABLE sat_product_codes
ADD COLUMN IF NOT EXISTS embedding vector(384);

-- Create IVFFlat index for fast cosine similarity search
-- Using lists = 100 which is appropriate for ~55,000 vectors
-- Formula: lists = sqrt(n) where n is number of rows
CREATE INDEX IF NOT EXISTS idx_sat_product_codes_embedding
  ON sat_product_codes USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Add comment explaining the column
COMMENT ON COLUMN sat_product_codes.embedding IS
  'Vector embedding (384 dimensions) generated by paraphrase-multilingual-MiniLM-L12-v2 model for semantic search';

-- Add similar column to sat_unit_codes for future use
ALTER TABLE sat_unit_codes
ADD COLUMN IF NOT EXISTS embedding vector(384);

CREATE INDEX IF NOT EXISTS idx_sat_unit_codes_embedding
  ON sat_unit_codes USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 50);

COMMENT ON COLUMN sat_unit_codes.embedding IS
  'Vector embedding (384 dimensions) for semantic search of unit codes';
